- name: My Playbok
  hosts: ansible_nodes
  remote_user: cloud_user
  become: yes
  tasks:
    - name: delete any existing git repo
      shell: rm -rf python-client-google-deployment-manager/
    - name: cloning git repo
      shell: git clone https://github.com/prudhvireddym/python-client-google-deployment-manager.git
    - name: Cloud SDK distribution URI as a package source
      shell: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    - name: Install packages
      apt:
        name:
        - apt-transport-https
        - ca-certificates
        - gnupg
        - python-pip
        state: latest
        update_cache: true
    - name: importing google cloud public key
      shell: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
    - name: upgrading and updating
      apt:
        upgrade: yes
        update_cache: yes
    - name: Installing google-cloud-sdk
      apt:
        name:
        - google-cloud-sdk
        state: latest
    - name: Change directory 
      command: chdir=/python-client-google-deployment-manager
    - name: Creating virtualenvironment ,activating it , installing dependencies
      shell: pip3 install venv | virtualenv venv | source venv/bin/activate | pip3 install -r requirements.txt | Python3 gcp-api-upgraded.py
