- name: My Playbok
  hosts: ansible_nodes
  remote_user: cloud_user
  become: true
  tasks:
    - name: Go to Desktop
      command: chdir= Desktop
    - name: cloning git repo
      shell: git clone https://github.com/prudhvireddym/python-client-google-deployment-manager.git
    - name: Install packages
      apt:
        name:
        - apt-transport-https
        - ca-certificates
        - gnupg
        state: latest
        update_cache: true
    - name: importing google cloud public key
      shell: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
    - name: Installing google-cloud-sdk
      apt:
        upgrad: yes
        update_cache: yes
        name:
        - google-cloud-sdk
        state: latest
